# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('customer_name', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(max_length=10)),
                ('website', models.URLField()),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'Mission Control'), (20, 'SSL Certificate'), (30, 'Infrastructure')])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
